version: "3.8"

services:
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qg

  kafka-setup:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - kafka
    command: >
      bash -c "
        echo 'Waiting for Kafka...' &&
        until kafka-topics --bootstrap-server kafka:29092 --list; do sleep 2; done &&
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic btc_trades_raw --partitions 1 --replication-factor 1 &&
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic btc_alerts --partitions 1 --replication-factor 1 &&
        echo 'Topics ready.'
      "

  flink-job:
    build: ./flink
    depends_on:
      kafka-setup:
        condition: service_completed_successfully
    environment:
      KAFKA_BOOTSTRAP_SERVERS_INTERNAL: kafka:29092
      KAFKA_TOPIC_RAW: btc_trades_raw
      KAFKA_TOPIC_ALERTS: btc_alerts
    restart: on-failure
